
name: build and deploy gh-pages

  push:
    branches:
      - master

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        with:
          keep_history: true
        env:
          ACCESS_TOKEN: ${{ secrets.commit_secret }}
          BRANCH: gh-pages
          FOLDER: build
          BUILD_SCRIPT: npm install && npm run test && npm run deploy
